server:
  port: 9080

spring:
  application:
    name: b-gateway

  cloud:
    gateway:
      routes:
        - id: b-oauth # 路由ID，保持唯一
          uri: lb://b-oauth # 目标服务地址
          predicates: # 断言（路由条件）
            - Path=/oauth/**
        - id: b-workflow # 路由ID，保持唯一
          uri: lb://b-workflow # 目标服务地址
          predicates: # 断言（路由条件）
            - Path=/b-workflow/**
        - id: app-mgr
          uri: lb://app-mgr # 目标服务地址
          predicates: # 断言（路由条件）
            - Path=/mgr/**
        - id: app-demo01 # 路由ID，保持唯一
          uri: lb://app-demo01 # 目标服务地址
          predicates: # 断言（路由条件）
            - Path=/app-demo01/**

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}