server:
  port: 8001
  servlet:
    context-path: /oauth

spring:
  application:
    name: b-oauth
  data:
    redis:
      host: light.bilegole.com
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
